ros2_serializer:
    ros__parameters:
        chatter:
            serial_mapping: 9
            type: std_msgs/String
            direction: SerialToROS2
        different:
            serial_mapping: 12
            type: std_msgs/String
            direction: SerialToROS2
        another:
            serial_mapping: 13
            type: std_msgs/String
            direction: ROS2ToSerial
